using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NetworkItemSyncModel
{
    [RealtimeProperty(1, true, true)]
    private string _key;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NetworkItemSyncModel : RealtimeModel {
    public string key {
        get {
            return _keyProperty.value;
        }
        set {
            if (_keyProperty.value == value) return;
            _keyProperty.value = value;
            InvalidateReliableLength();
            FireKeyDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(NetworkItemSyncModel model, T value);
    public event PropertyChangedHandler<string> keyDidChange;
    
    public enum PropertyID : uint {
        Key = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _keyProperty;
    
    #endregion
    
    public NetworkItemSyncModel() : base(null) {
        _keyProperty = new ReliableProperty<string>(1, _key);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _keyProperty.UnsubscribeCallback();
    }
    
    private void FireKeyDidChange(string value) {
        try {
            keyDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _keyProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _keyProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Key: {
                    changed = _keyProperty.Read(stream, context);
                    if (changed) FireKeyDidChange(key);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _key = key;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
